### ISSUE TITLE
It is possible to add a section on general challenges?

### ISSUE THREAD

**Issue by GeraldineGomez** [CarmenTamayo/100_days_vignette#13]
In the discussions at the event, some general challenges were mentioned that can affect the response in this kind of scenarios, such as lack of knowledge of version control tools, language barriers in documentation, epidemiological and programming training, infrastructure, etc.

**Comment by CarmenTamayo** [comment]
Thank you Geraldine, these issues will be added to the perspective piece, that we will share with you shortly 😊

From: GeraldineGomez ***@***.***>
Date: Thursday, 23 February 2023 at 14:59
To: CarmenTamayo/100_days_vignette ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CarmenTamayo/100_days_vignette] It is possible to add a section on general challenges? (Issue #13)

In the discussions at the event, some general challenges were mentioned that can affect the response in this kind of scenarios, such as lack of knowledge of version control tools, language barriers in documentation, epidemiological and programming training, infrastructure, etc.
