### ISSUE TITLE
Scenario 4 (analysed by group 5)

### ISSUE THREAD

**Issue by davidsantiagoquevedo** [CarmenTamayo/100_days_vignette#14]
Hi, I suggest adding to the description of the pipeline `lubridate` and `tidyverse` for the data cleaning process.
Also, for the challenges, due to the lack of information on the serial interval, we tried the values for covid-19 (6.48 days) and flu (2.9 days). We found in the severity analysis, that the death rate of our simulated outbreak was similar to seasonal flu.

**Comment by CarmenTamayo** [comment]
Gracias David! I've added your suggestions to the vignette
